project_id = "wruizzwgevxdsaiblmsd"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.generate-lesson-audio]
verify_jwt = false

[functions.generate-lesson-images]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.generate-quiz-audio]
verify_jwt = false

[functions.paypal-client-token]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.send-marketing-email]
verify_jwt = false

[functions.translate-lesson-titles]
verify_jwt = false

[functions.send-affiliate-welcome-email]
verify_jwt = false
