project_id = "wruizzwgevxdsaiblmsd"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false
